export const NIGERIAN_BANKS = [
  "Access Bank",
  "Access Bank (Diamond)",
  "ALAT by WEMA",
  "ASO Savings and Loans",
  "Banque Misr",
  "Bowen Microfinance Bank",
  "Carbon",
  "Ceepos Cooperative",
  "Chanelle Microfinance Bank",
  "Citibank Nigeria",
  "Cloudnect",
  "Coronation Merchant Bank",
  "Cosmopolitan Microfinance Bank",
  "Credit Direct",
  "EcoBank",
  "Ekondo Microfinance Bank",
  "Fidelity Bank",
  "First Bank of Nigeria",
  "First City Monument Bank (FCMB)",
  "FSDH Merchant Bank",
  "Globus Bank",
  "GoMoney",
  "Guaranty Trust Bank (GTBank)",
  "Hackman Microfinance Bank",
  "Hasal Microfinance Bank",
  "Heritage Bank",
  "Hope Payment Service Bank",
  "Ibile Microfinance Bank",
  "Infinity MFB",
  "Jaiz Bank",
  "Kegov MFB",
  "Keystone Bank",
  "Kredi Bank",
  "Kuda Bank",
  "Lapo MFB",
  "Lavango Microfinance Bank",
  "Mayfair MFB",
  "Mint Finex MFB",
  "MoneyMaster PSB",
  "N M B",
  "NPF Microfinance Bank",
  "One Finance",
  "Palmpay",
  "Paga",
  "Parallex Bank",
  "Parkway - ReadyCash",
  "Paycom (Opay)",
  "Paystack",
  "Polaris Bank",
  "Premium Trust Bank",
  "Providus Bank",
  "Rand Merchant Bank",
  "Rubies Bank",
  "Signal Trust MFB",
  "Solid Allianze MFB",
  "Sparkle Microfinance Bank",
  "Stanbic IBTC Bank",
  "Standard Chartered Bank",
  "Sterling Bank",
  "Suntrust Bank",
  "TAJ Bank",
  "Tangerine Money",
  "TCF MFB",
  "Titan Bank",
  "Trustbond Microfinance Bank",
  "Union Bank of Nigeria",
  "United Bank for Africa (UBA)",
  "Unity Bank",
  "VFD Microfinance Bank",
  "Wema Bank",
  "Zenith Bank",
];